// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: bitoroprotocol/stats/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is a request type for the Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5798304f0058c03, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is a response type for the Params RPC method.
type QueryParamsResponse struct {
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5798304f0058c03, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// QueryStatsMetadataRequest is a request type for the StatsMetadata RPC method.
type QueryStatsMetadataRequest struct {
}

func (m *QueryStatsMetadataRequest) Reset()         { *m = QueryStatsMetadataRequest{} }
func (m *QueryStatsMetadataRequest) String() string { return proto.CompactTextString(m) }
func (*QueryStatsMetadataRequest) ProtoMessage()    {}
func (*QueryStatsMetadataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5798304f0058c03, []int{2}
}
func (m *QueryStatsMetadataRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryStatsMetadataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryStatsMetadataRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryStatsMetadataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryStatsMetadataRequest.Merge(m, src)
}
func (m *QueryStatsMetadataRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryStatsMetadataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryStatsMetadataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryStatsMetadataRequest proto.InternalMessageInfo

// QueryStatsMetadataResponse is a response type for the StatsMetadata RPC
// method.
type QueryStatsMetadataResponse struct {
	Metadata *StatsMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (m *QueryStatsMetadataResponse) Reset()         { *m = QueryStatsMetadataResponse{} }
func (m *QueryStatsMetadataResponse) String() string { return proto.CompactTextString(m) }
func (*QueryStatsMetadataResponse) ProtoMessage()    {}
func (*QueryStatsMetadataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5798304f0058c03, []int{3}
}
func (m *QueryStatsMetadataResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryStatsMetadataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryStatsMetadataResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryStatsMetadataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryStatsMetadataResponse.Merge(m, src)
}
func (m *QueryStatsMetadataResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryStatsMetadataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryStatsMetadataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryStatsMetadataResponse proto.InternalMessageInfo

func (m *QueryStatsMetadataResponse) GetMetadata() *StatsMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

// QueryGlobalStatsRequest is a request type for the GlobalStats RPC method.
type QueryGlobalStatsRequest struct {
}

func (m *QueryGlobalStatsRequest) Reset()         { *m = QueryGlobalStatsRequest{} }
func (m *QueryGlobalStatsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGlobalStatsRequest) ProtoMessage()    {}
func (*QueryGlobalStatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5798304f0058c03, []int{4}
}
func (m *QueryGlobalStatsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGlobalStatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGlobalStatsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGlobalStatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGlobalStatsRequest.Merge(m, src)
}
func (m *QueryGlobalStatsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGlobalStatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGlobalStatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGlobalStatsRequest proto.InternalMessageInfo

// QueryGlobalStatsResponse is a response type for the GlobalStats RPC method.
type QueryGlobalStatsResponse struct {
	Stats *GlobalStats `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
}

func (m *QueryGlobalStatsResponse) Reset()         { *m = QueryGlobalStatsResponse{} }
func (m *QueryGlobalStatsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGlobalStatsResponse) ProtoMessage()    {}
func (*QueryGlobalStatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5798304f0058c03, []int{5}
}
func (m *QueryGlobalStatsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGlobalStatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGlobalStatsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGlobalStatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGlobalStatsResponse.Merge(m, src)
}
func (m *QueryGlobalStatsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGlobalStatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGlobalStatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGlobalStatsResponse proto.InternalMessageInfo

func (m *QueryGlobalStatsResponse) GetStats() *GlobalStats {
	if m != nil {
		return m.Stats
	}
	return nil
}

// QueryUserStatsRequest is a request type for the UserStats RPC method.
type QueryUserStatsRequest struct {
	User string `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (m *QueryUserStatsRequest) Reset()         { *m = QueryUserStatsRequest{} }
func (m *QueryUserStatsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryUserStatsRequest) ProtoMessage()    {}
func (*QueryUserStatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5798304f0058c03, []int{6}
}
func (m *QueryUserStatsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryUserStatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryUserStatsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryUserStatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryUserStatsRequest.Merge(m, src)
}
func (m *QueryUserStatsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryUserStatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryUserStatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryUserStatsRequest proto.InternalMessageInfo

func (m *QueryUserStatsRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

// QueryUserStatsResponse is a request type for the UserStats RPC method.
type QueryUserStatsResponse struct {
	Stats *UserStats `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
}

func (m *QueryUserStatsResponse) Reset()         { *m = QueryUserStatsResponse{} }
func (m *QueryUserStatsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryUserStatsResponse) ProtoMessage()    {}
func (*QueryUserStatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5798304f0058c03, []int{7}
}
func (m *QueryUserStatsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryUserStatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryUserStatsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryUserStatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryUserStatsResponse.Merge(m, src)
}
func (m *QueryUserStatsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryUserStatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryUserStatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryUserStatsResponse proto.InternalMessageInfo

func (m *QueryUserStatsResponse) GetStats() *UserStats {
	if m != nil {
		return m.Stats
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "bitoroprotocol.stats.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "bitoroprotocol.stats.QueryParamsResponse")
	proto.RegisterType((*QueryStatsMetadataRequest)(nil), "bitoroprotocol.stats.QueryStatsMetadataRequest")
	proto.RegisterType((*QueryStatsMetadataResponse)(nil), "bitoroprotocol.stats.QueryStatsMetadataResponse")
	proto.RegisterType((*QueryGlobalStatsRequest)(nil), "bitoroprotocol.stats.QueryGlobalStatsRequest")
	proto.RegisterType((*QueryGlobalStatsResponse)(nil), "bitoroprotocol.stats.QueryGlobalStatsResponse")
	proto.RegisterType((*QueryUserStatsRequest)(nil), "bitoroprotocol.stats.QueryUserStatsRequest")
	proto.RegisterType((*QueryUserStatsResponse)(nil), "bitoroprotocol.stats.QueryUserStatsResponse")
}

func init() { proto.RegisterFile("bitoroprotocol/stats/query.proto", fileDescriptor_d5798304f0058c03) }

var fileDescriptor_d5798304f0058c03 = []byte{
	// 502 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xc1, 0x6b, 0x13, 0x41,
	0x14, 0xc6, 0x33, 0x92, 0x06, 0xfb, 0x8a, 0x97, 0x31, 0x6a, 0xbb, 0x86, 0x6d, 0x3a, 0x06, 0x89,
	0xb6, 0xdd, 0x91, 0x8a, 0x0a, 0x5e, 0x84, 0x5e, 0x3c, 0x89, 0x6d, 0x8a, 0x17, 0x41, 0xca, 0x24,
	0x0e, 0xdb, 0xc5, 0x64, 0x67, 0xbb, 0x33, 0x41, 0x7b, 0xd5, 0x7f, 0xa0, 0xe0, 0xc5, 0xa3, 0x7f,
	0x4e, 0x8f, 0x05, 0x2f, 0x9e, 0x8a, 0x24, 0xfe, 0x21, 0x92, 0x37, 0x93, 0x98, 0x4d, 0xa6, 0x21,
	0x97, 0xb0, 0x79, 0xfb, 0x7d, 0xdf, 0xef, 0x0b, 0xef, 0x05, 0xea, 0xed, 0xc4, 0xa8, 0x5c, 0x65,
	0xb9, 0x32, 0xaa, 0xa3, 0xba, 0x5c, 0x1b, 0x61, 0x34, 0x3f, 0xed, 0xcb, 0xfc, 0x2c, 0xc2, 0x21,
	0xad, 0x16, 0x15, 0x11, 0x2a, 0x82, 0x6a, 0xac, 0x62, 0x3b, 0xe3, 0xa3, 0x27, 0xab, 0x0d, 0x6a,
	0xb1, 0x52, 0x71, 0x57, 0x72, 0x91, 0x25, 0x5c, 0xa4, 0xa9, 0x32, 0xc2, 0x24, 0x2a, 0xd5, 0xee,
	0xed, 0x96, 0x97, 0x95, 0x89, 0x5c, 0xf4, 0xc6, 0x12, 0x7f, 0x1d, 0xfc, 0xb4, 0x0a, 0x56, 0x05,
	0x7a, 0x38, 0x6a, 0x77, 0x80, 0xb6, 0x96, 0x3c, 0xed, 0x4b, 0x6d, 0xd8, 0x21, 0xdc, 0x2e, 0x4c,
	0x75, 0xa6, 0x52, 0x2d, 0xe9, 0x4b, 0xa8, 0xd8, 0xf8, 0x75, 0x52, 0x27, 0xcd, 0xb5, 0xbd, 0x5a,
	0xe4, 0xfb, 0x31, 0x91, 0x75, 0xed, 0x97, 0x2f, 0xae, 0x36, 0x4b, 0x2d, 0xe7, 0x60, 0xf7, 0x61,
	0x03, 0x23, 0x8f, 0x46, 0x92, 0x37, 0xd2, 0x88, 0x8f, 0xc2, 0x88, 0x31, 0xef, 0x03, 0x04, 0xbe,
	0x97, 0x0e, 0xfb, 0x0a, 0x6e, 0xf6, 0xdc, 0xcc, 0x81, 0x1f, 0xf8, 0xc1, 0x45, 0xfb, 0xc4, 0xc4,
	0x36, 0xe0, 0x1e, 0xc6, 0xbf, 0xee, 0xaa, 0xb6, 0xe8, 0xa2, 0x6a, 0x4c, 0x3e, 0x82, 0xf5, 0xf9,
	0x57, 0x8e, 0xfb, 0x02, 0x56, 0x30, 0xd7, 0x41, 0xb7, 0xfc, 0xd0, 0x69, 0xa7, 0xd5, 0xb3, 0x6d,
	0xb8, 0x83, 0xa1, 0xef, 0xb4, 0xcc, 0xa7, 0x69, 0x94, 0x42, 0xb9, 0xaf, 0x65, 0x8e, 0x81, 0xab,
	0x2d, 0x7c, 0x66, 0x6f, 0xe1, 0xee, 0xac, 0xd8, 0xf1, 0x9f, 0x15, 0xf9, 0x9b, 0x7e, 0xfe, 0x7f,
	0x9f, 0x55, 0xef, 0x5d, 0x95, 0x61, 0x05, 0x13, 0xe9, 0x37, 0x02, 0x15, 0xbb, 0x0c, 0xda, 0xf4,
	0x9b, 0xe7, 0x77, 0x1f, 0x3c, 0x5a, 0x42, 0x69, 0x0b, 0xb2, 0xc6, 0xd7, 0x5f, 0x7f, 0xbf, 0xdf,
	0x08, 0x69, 0x8d, 0x2f, 0x38, 0x45, 0xfa, 0x93, 0xc0, 0xad, 0xc2, 0x66, 0x28, 0x5f, 0x80, 0xf0,
	0xdd, 0x47, 0xf0, 0x64, 0x79, 0x83, 0xab, 0xb6, 0x83, 0xd5, 0x1e, 0xd2, 0x06, 0xbf, 0xfe, 0x2f,
	0x70, 0x3c, 0x3e, 0x10, 0xfa, 0x83, 0xc0, 0xda, 0xd4, 0x1e, 0xe9, 0xee, 0x02, 0xde, 0xfc, 0x11,
	0x05, 0xd1, 0xb2, 0x72, 0x57, 0xee, 0x31, 0x96, 0x6b, 0x50, 0xe6, 0x2f, 0x17, 0xa3, 0xe5, 0x18,
	0xbf, 0xd0, 0x73, 0x02, 0xab, 0x93, 0x15, 0xd3, 0xed, 0x05, 0xa4, 0xd9, 0x6b, 0x0b, 0x76, 0x96,
	0x13, 0xbb, 0x52, 0x4d, 0x2c, 0xc5, 0x68, 0xdd, 0x5f, 0x6a, 0x74, 0xab, 0xb6, 0xd2, 0xfe, 0xc1,
	0xc5, 0x20, 0x24, 0x97, 0x83, 0x90, 0xfc, 0x19, 0x84, 0xe4, 0x7c, 0x18, 0x96, 0x2e, 0x87, 0x61,
	0xe9, 0xf7, 0x30, 0x2c, 0xbd, 0x7f, 0x1e, 0x27, 0xe6, 0xa4, 0xdf, 0x8e, 0x3a, 0xaa, 0xe7, 0x52,
	0x76, 0x53, 0x69, 0x3e, 0xab, 0xfc, 0x13, 0xef, 0x9c, 0x88, 0x24, 0xe5, 0x93, 0xd0, 0x2f, 0x2e,
	0xd6, 0x9c, 0x65, 0x52, 0xb7, 0x2b, 0x38, 0x7f, 0xfa, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xd1, 0x57,
	0x36, 0xa4, 0x3f, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Queries the Params.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries StatsMetadata.
	StatsMetadata(ctx context.Context, in *QueryStatsMetadataRequest, opts ...grpc.CallOption) (*QueryStatsMetadataResponse, error)
	// Queries GlobalStats.
	GlobalStats(ctx context.Context, in *QueryGlobalStatsRequest, opts ...grpc.CallOption) (*QueryGlobalStatsResponse, error)
	// Queries UserStats.
	UserStats(ctx context.Context, in *QueryUserStatsRequest, opts ...grpc.CallOption) (*QueryUserStatsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/bitoroprotocol.stats.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) StatsMetadata(ctx context.Context, in *QueryStatsMetadataRequest, opts ...grpc.CallOption) (*QueryStatsMetadataResponse, error) {
	out := new(QueryStatsMetadataResponse)
	err := c.cc.Invoke(ctx, "/bitoroprotocol.stats.Query/StatsMetadata", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GlobalStats(ctx context.Context, in *QueryGlobalStatsRequest, opts ...grpc.CallOption) (*QueryGlobalStatsResponse, error) {
	out := new(QueryGlobalStatsResponse)
	err := c.cc.Invoke(ctx, "/bitoroprotocol.stats.Query/GlobalStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) UserStats(ctx context.Context, in *QueryUserStatsRequest, opts ...grpc.CallOption) (*QueryUserStatsResponse, error) {
	out := new(QueryUserStatsResponse)
	err := c.cc.Invoke(ctx, "/bitoroprotocol.stats.Query/UserStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Queries the Params.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries StatsMetadata.
	StatsMetadata(context.Context, *QueryStatsMetadataRequest) (*QueryStatsMetadataResponse, error)
	// Queries GlobalStats.
	GlobalStats(context.Context, *QueryGlobalStatsRequest) (*QueryGlobalStatsResponse, error)
	// Queries UserStats.
	UserStats(context.Context, *QueryUserStatsRequest) (*QueryUserStatsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) StatsMetadata(ctx context.Context, req *QueryStatsMetadataRequest) (*QueryStatsMetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StatsMetadata not implemented")
}
func (*UnimplementedQueryServer) GlobalStats(ctx context.Context, req *QueryGlobalStatsRequest) (*QueryGlobalStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GlobalStats not implemented")
}
func (*UnimplementedQueryServer) UserStats(ctx context.Context, req *QueryUserStatsRequest) (*QueryUserStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserStats not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bitoroprotocol.stats.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_StatsMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryStatsMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).StatsMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bitoroprotocol.stats.Query/StatsMetadata",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).StatsMetadata(ctx, req.(*QueryStatsMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GlobalStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGlobalStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GlobalStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bitoroprotocol.stats.Query/GlobalStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GlobalStats(ctx, req.(*QueryGlobalStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_UserStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryUserStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).UserStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bitoroprotocol.stats.Query/UserStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).UserStats(ctx, req.(*QueryUserStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bitoroprotocol.stats.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "StatsMetadata",
			Handler:    _Query_StatsMetadata_Handler,
		},
		{
			MethodName: "GlobalStats",
			Handler:    _Query_GlobalStats_Handler,
		},
		{
			MethodName: "UserStats",
			Handler:    _Query_UserStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bitoroprotocol/stats/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryStatsMetadataRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryStatsMetadataRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryStatsMetadataRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryStatsMetadataResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryStatsMetadataResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryStatsMetadataResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Metadata != nil {
		{
			size, err := m.Metadata.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGlobalStatsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGlobalStatsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGlobalStatsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryGlobalStatsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGlobalStatsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGlobalStatsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Stats != nil {
		{
			size, err := m.Stats.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryUserStatsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryUserStatsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryUserStatsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.User) > 0 {
		i -= len(m.User)
		copy(dAtA[i:], m.User)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.User)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryUserStatsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryUserStatsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryUserStatsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Stats != nil {
		{
			size, err := m.Stats.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryStatsMetadataRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryStatsMetadataResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Metadata != nil {
		l = m.Metadata.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGlobalStatsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryGlobalStatsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Stats != nil {
		l = m.Stats.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryUserStatsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.User)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryUserStatsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Stats != nil {
		l = m.Stats.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryStatsMetadataRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryStatsMetadataRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryStatsMetadataRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryStatsMetadataResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryStatsMetadataResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryStatsMetadataResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metadata", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Metadata == nil {
				m.Metadata = &StatsMetadata{}
			}
			if err := m.Metadata.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGlobalStatsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGlobalStatsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGlobalStatsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGlobalStatsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGlobalStatsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGlobalStatsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Stats", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Stats == nil {
				m.Stats = &GlobalStats{}
			}
			if err := m.Stats.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryUserStatsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryUserStatsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryUserStatsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field User", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.User = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryUserStatsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryUserStatsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryUserStatsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Stats", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Stats == nil {
				m.Stats = &UserStats{}
			}
			if err := m.Stats.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
