// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: bitoroprotocol/listing/params.proto

package types

import (
	fmt "fmt"
	github_com_bitoro_network_chain_protocol_dtypes "github.com/bitoro-network/chain/protocol/dtypes"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ListingVaultDepositParams represents the params for PML megavault deposits
type ListingVaultDepositParams struct {
	// Amount that will be deposited into the new market vault exclusively
	NewVaultDepositAmount github_com_bitoro_network_chain_protocol_dtypes.SerializableInt `protobuf:"bytes,1,opt,name=new_vault_deposit_amount,json=newVaultDepositAmount,proto3,customtype=github.com/bitoro-network/chain/protocol/dtypes.SerializableInt" json:"new_vault_deposit_amount"`
	// Amount deposited into the main vault exclusively. This amount does not
	// include the amount deposited into the new vault.
	MainVaultDepositAmount github_com_bitoro_network_chain_protocol_dtypes.SerializableInt `protobuf:"bytes,2,opt,name=main_vault_deposit_amount,json=mainVaultDepositAmount,proto3,customtype=github.com/bitoro-network/chain/protocol/dtypes.SerializableInt" json:"main_vault_deposit_amount"`
	// Lockup period for this deposit
	NumBlocksToLockShares uint32 `protobuf:"varint,3,opt,name=num_blocks_to_lock_shares,json=numBlocksToLockShares,proto3" json:"num_blocks_to_lock_shares,omitempty"`
}

func (m *ListingVaultDepositParams) Reset()         { *m = ListingVaultDepositParams{} }
func (m *ListingVaultDepositParams) String() string { return proto.CompactTextString(m) }
func (*ListingVaultDepositParams) ProtoMessage()    {}
func (*ListingVaultDepositParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_31ae7b115e7440e2, []int{0}
}
func (m *ListingVaultDepositParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ListingVaultDepositParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ListingVaultDepositParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ListingVaultDepositParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListingVaultDepositParams.Merge(m, src)
}
func (m *ListingVaultDepositParams) XXX_Size() int {
	return m.Size()
}
func (m *ListingVaultDepositParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ListingVaultDepositParams.DiscardUnknown(m)
}

var xxx_messageInfo_ListingVaultDepositParams proto.InternalMessageInfo

func (m *ListingVaultDepositParams) GetNumBlocksToLockShares() uint32 {
	if m != nil {
		return m.NumBlocksToLockShares
	}
	return 0
}

func init() {
	proto.RegisterType((*ListingVaultDepositParams)(nil), "bitoroprotocol.listing.ListingVaultDepositParams")
}

func init() {
	proto.RegisterFile("bitoroprotocol/listing/params.proto", fileDescriptor_31ae7b115e7440e2)
}

var fileDescriptor_31ae7b115e7440e2 = []byte{
	// 310 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x91, 0x31, 0x4b, 0x03, 0x31,
	0x14, 0x80, 0x2f, 0x15, 0x1c, 0x0e, 0x5d, 0x8a, 0x2d, 0xad, 0x43, 0x5a, 0x74, 0xe9, 0xe2, 0x65,
	0x70, 0xe9, 0x26, 0x16, 0x41, 0x84, 0x0e, 0xd2, 0x8a, 0x83, 0x4b, 0xc8, 0x5d, 0xc3, 0x35, 0x34,
	0xc9, 0x3b, 0x92, 0x9c, 0x55, 0x27, 0xf1, 0x17, 0xf8, 0xb3, 0x3a, 0x76, 0x14, 0xc1, 0x22, 0xbd,
	0x3f, 0x22, 0x97, 0x93, 0xa2, 0xd0, 0xc1, 0xc1, 0xed, 0xf1, 0xbe, 0x8f, 0xbc, 0x0f, 0x12, 0x1e,
	0xc7, 0xc2, 0x81, 0x81, 0xcc, 0x80, 0x83, 0x04, 0x24, 0x91, 0xc2, 0x3a, 0xa1, 0x53, 0x92, 0x31,
	0xc3, 0x94, 0x8d, 0xfc, 0xbe, 0xde, 0xfc, 0x2d, 0x45, 0xdf, 0xd2, 0xe1, 0x41, 0x0a, 0x69, 0xb5,
	0x25, 0xe5, 0x54, 0xd9, 0x47, 0x1f, 0xb5, 0xb0, 0x3d, 0xac, 0x8c, 0x5b, 0x96, 0x4b, 0x77, 0xc1,
	0x33, 0xb0, 0xc2, 0x5d, 0xfb, 0x17, 0xeb, 0xcf, 0x28, 0x6c, 0x69, 0x3e, 0xa7, 0xf7, 0x25, 0xa2,
	0x93, 0x8a, 0x51, 0xa6, 0x20, 0xd7, 0xae, 0x85, 0xba, 0xa8, 0xb7, 0x37, 0xb8, 0x5c, 0xac, 0x3a,
	0xc1, 0xfb, 0xaa, 0x73, 0x96, 0x0a, 0x37, 0xcd, 0xe3, 0x28, 0x01, 0x45, 0xaa, 0x82, 0x13, 0xcd,
	0xdd, 0x1c, 0xcc, 0x8c, 0x24, 0x53, 0x26, 0x34, 0xd9, 0x54, 0x4f, 0xdc, 0x63, 0xc6, 0x6d, 0x34,
	0xe6, 0x46, 0x30, 0x29, 0x9e, 0x58, 0x2c, 0xf9, 0x95, 0x76, 0xa3, 0x86, 0xe6, 0xf3, 0x9f, 0x09,
	0xe7, 0xfe, 0x4a, 0xfd, 0x05, 0x85, 0x6d, 0xc5, 0x84, 0xde, 0xde, 0x50, 0xfb, 0xdf, 0x86, 0x66,
	0x79, 0x69, 0x4b, 0x44, 0x3f, 0x6c, 0xeb, 0x5c, 0xd1, 0x58, 0x42, 0x32, 0xb3, 0xd4, 0x01, 0x2d,
	0x07, 0x6a, 0xa7, 0xcc, 0x70, 0xdb, 0xda, 0xe9, 0xa2, 0xde, 0xfe, 0xa8, 0xa1, 0x73, 0x35, 0xf0,
	0xfc, 0x06, 0x86, 0x90, 0xcc, 0xc6, 0x1e, 0x0e, 0x46, 0x8b, 0x35, 0x46, 0xcb, 0x35, 0x46, 0x9f,
	0x6b, 0x8c, 0x5e, 0x0b, 0x1c, 0x2c, 0x0b, 0x1c, 0xbc, 0x15, 0x38, 0xb8, 0xeb, 0xff, 0x39, 0xf6,
	0x61, 0xf3, 0xd1, 0xbe, 0x3a, 0xde, 0xf5, 0xe4, 0xf4, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x96, 0x8b,
	0xaa, 0x67, 0x0f, 0x02, 0x00, 0x00,
}

func (m *ListingVaultDepositParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ListingVaultDepositParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ListingVaultDepositParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.NumBlocksToLockShares != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.NumBlocksToLockShares))
		i--
		dAtA[i] = 0x18
	}
	{
		size := m.MainVaultDepositAmount.Size()
		i -= size
		if _, err := m.MainVaultDepositAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.NewVaultDepositAmount.Size()
		i -= size
		if _, err := m.NewVaultDepositAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ListingVaultDepositParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.NewVaultDepositAmount.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.MainVaultDepositAmount.Size()
	n += 1 + l + sovParams(uint64(l))
	if m.NumBlocksToLockShares != 0 {
		n += 1 + sovParams(uint64(m.NumBlocksToLockShares))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ListingVaultDepositParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ListingVaultDepositParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ListingVaultDepositParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewVaultDepositAmount", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.NewVaultDepositAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MainVaultDepositAmount", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MainVaultDepositAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NumBlocksToLockShares", wireType)
			}
			m.NumBlocksToLockShares = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NumBlocksToLockShares |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
