// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: bitoroprotocol/delaymsg/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/codec/types"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgDelayMessage is a request type for the DelayMessage method.
type MsgDelayMessage struct {
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// The message to be delayed.
	Msg *types.Any `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	// The number of blocks to delay the message for.
	DelayBlocks uint32 `protobuf:"varint,3,opt,name=delay_blocks,json=delayBlocks,proto3" json:"delay_blocks,omitempty"`
}

func (m *MsgDelayMessage) Reset()         { *m = MsgDelayMessage{} }
func (m *MsgDelayMessage) String() string { return proto.CompactTextString(m) }
func (*MsgDelayMessage) ProtoMessage()    {}
func (*MsgDelayMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_e80dda986330def2, []int{0}
}
func (m *MsgDelayMessage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDelayMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDelayMessage.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDelayMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDelayMessage.Merge(m, src)
}
func (m *MsgDelayMessage) XXX_Size() int {
	return m.Size()
}
func (m *MsgDelayMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDelayMessage.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDelayMessage proto.InternalMessageInfo

func (m *MsgDelayMessage) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgDelayMessage) GetMsg() *types.Any {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *MsgDelayMessage) GetDelayBlocks() uint32 {
	if m != nil {
		return m.DelayBlocks
	}
	return 0
}

// MsgDelayMessageResponse is a response type for the DelayMessage method.
type MsgDelayMessageResponse struct {
	// The id of the created delayed message.
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgDelayMessageResponse) Reset()         { *m = MsgDelayMessageResponse{} }
func (m *MsgDelayMessageResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDelayMessageResponse) ProtoMessage()    {}
func (*MsgDelayMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e80dda986330def2, []int{1}
}
func (m *MsgDelayMessageResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDelayMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDelayMessageResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDelayMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDelayMessageResponse.Merge(m, src)
}
func (m *MsgDelayMessageResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDelayMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDelayMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDelayMessageResponse proto.InternalMessageInfo

func (m *MsgDelayMessageResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*MsgDelayMessage)(nil), "bitoroprotocol.delaymsg.MsgDelayMessage")
	proto.RegisterType((*MsgDelayMessageResponse)(nil), "bitoroprotocol.delaymsg.MsgDelayMessageResponse")
}

func init() { proto.RegisterFile("bitoroprotocol/delaymsg/tx.proto", fileDescriptor_e80dda986330def2) }

var fileDescriptor_e80dda986330def2 = []byte{
	// 360 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xcd, 0x4e, 0xc2, 0x40,
	0x18, 0x64, 0xc1, 0x98, 0xb0, 0x20, 0x26, 0x0d, 0x09, 0x85, 0x43, 0x53, 0x39, 0x98, 0x6a, 0xc2,
	0xae, 0x62, 0x62, 0xa2, 0x37, 0x88, 0x57, 0x2e, 0xe5, 0xe6, 0x85, 0xf4, 0x67, 0x5d, 0x56, 0xda,
	0x2e, 0x76, 0x17, 0xa5, 0x57, 0x9f, 0xc0, 0x87, 0xf0, 0x01, 0x3c, 0xf8, 0x10, 0x1e, 0x89, 0x27,
	0x8f, 0x06, 0x0e, 0xbe, 0x86, 0xe9, 0x16, 0x44, 0x48, 0x4c, 0x3c, 0x35, 0xdf, 0xcc, 0x74, 0x66,
	0xbe, 0xcd, 0x07, 0x4d, 0x97, 0x49, 0x1e, 0xf3, 0x71, 0xcc, 0x25, 0xf7, 0x78, 0x80, 0x7d, 0x12,
	0x38, 0x49, 0x28, 0x28, 0x96, 0x53, 0xa4, 0x40, 0xad, 0xb6, 0xa9, 0x40, 0x2b, 0x45, 0xa3, 0xee,
	0x71, 0x11, 0x72, 0x31, 0x50, 0x0c, 0xce, 0x86, 0xec, 0x9f, 0x46, 0x2d, 0x9b, 0x70, 0x6a, 0x74,
	0x7f, 0x9a, 0x7e, 0x96, 0x44, 0x9d, 0x72, 0x4e, 0x03, 0x82, 0xd5, 0xe4, 0x4e, 0x6e, 0xb0, 0x13,
	0x25, 0x19, 0xd5, 0x7c, 0x06, 0x70, 0xbf, 0x27, 0xe8, 0x55, 0x6a, 0xdf, 0x23, 0x42, 0x38, 0x94,
	0x68, 0xe7, 0xb0, 0xe8, 0x4c, 0xe4, 0x90, 0xc7, 0x4c, 0x26, 0x3a, 0x30, 0x81, 0x55, 0xec, 0xea,
	0xef, 0xaf, 0xad, 0xea, 0x32, 0xac, 0xe3, 0xfb, 0x31, 0x11, 0xa2, 0x2f, 0x63, 0x16, 0x51, 0x7b,
	0x2d, 0xd5, 0x0e, 0x61, 0x21, 0x14, 0x54, 0xcf, 0x9b, 0xc0, 0x2a, 0xb5, 0xab, 0x28, 0x0b, 0x45,
	0xab, 0x50, 0xd4, 0x89, 0x12, 0x3b, 0x15, 0x68, 0x07, 0xb0, 0xac, 0xd6, 0x19, 0xb8, 0x01, 0xf7,
	0x46, 0x42, 0x2f, 0x98, 0xc0, 0xda, 0xb3, 0x4b, 0x0a, 0xeb, 0x2a, 0xe8, 0xb2, 0xf2, 0xf8, 0xf5,
	0x72, 0xbc, 0xb6, 0x6e, 0x1e, 0xc1, 0xda, 0x56, 0x4b, 0x9b, 0x88, 0x31, 0x8f, 0x04, 0xd1, 0x2a,
	0x30, 0xcf, 0x7c, 0x55, 0x73, 0xc7, 0xce, 0x33, 0xbf, 0x7d, 0x07, 0x0b, 0x3d, 0x41, 0xb5, 0x5b,
	0x58, 0xde, 0x58, 0xca, 0x42, 0x7f, 0xbc, 0x28, 0xda, 0x32, 0x6e, 0x9c, 0xfc, 0x57, 0xb9, 0xaa,
	0xd0, 0xed, 0xbf, 0xcd, 0x0d, 0x30, 0x9b, 0x1b, 0xe0, 0x73, 0x6e, 0x80, 0xa7, 0x85, 0x91, 0x9b,
	0x2d, 0x8c, 0xdc, 0xc7, 0xc2, 0xc8, 0x5d, 0x5f, 0x50, 0x26, 0x87, 0x13, 0x17, 0x79, 0x3c, 0xc4,
	0x99, 0x6b, 0x2b, 0x22, 0xf2, 0x81, 0xc7, 0x23, 0xec, 0x0d, 0x1d, 0x16, 0xe1, 0x9f, 0x13, 0x98,
	0xfe, 0x3a, 0x82, 0x64, 0x4c, 0x84, 0xbb, 0xab, 0xa8, 0xb3, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xcc, 0xe4, 0xea, 0x86, 0x2c, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// DelayMessage delays the execution of a message for a given number of
	// blocks.
	DelayMessage(ctx context.Context, in *MsgDelayMessage, opts ...grpc.CallOption) (*MsgDelayMessageResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) DelayMessage(ctx context.Context, in *MsgDelayMessage, opts ...grpc.CallOption) (*MsgDelayMessageResponse, error) {
	out := new(MsgDelayMessageResponse)
	err := c.cc.Invoke(ctx, "/bitoroprotocol.delaymsg.Msg/DelayMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// DelayMessage delays the execution of a message for a given number of
	// blocks.
	DelayMessage(context.Context, *MsgDelayMessage) (*MsgDelayMessageResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) DelayMessage(ctx context.Context, req *MsgDelayMessage) (*MsgDelayMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelayMessage not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_DelayMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDelayMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DelayMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bitoroprotocol.delaymsg.Msg/DelayMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DelayMessage(ctx, req.(*MsgDelayMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bitoroprotocol.delaymsg.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DelayMessage",
			Handler:    _Msg_DelayMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bitoroprotocol/delaymsg/tx.proto",
}

func (m *MsgDelayMessage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDelayMessage) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDelayMessage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DelayBlocks != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.DelayBlocks))
		i--
		dAtA[i] = 0x18
	}
	if m.Msg != nil {
		{
			size, err := m.Msg.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDelayMessageResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDelayMessageResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDelayMessageResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgDelayMessage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Msg != nil {
		l = m.Msg.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	if m.DelayBlocks != 0 {
		n += 1 + sovTx(uint64(m.DelayBlocks))
	}
	return n
}

func (m *MsgDelayMessageResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgDelayMessage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDelayMessage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDelayMessage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Msg", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Msg == nil {
				m.Msg = &types.Any{}
			}
			if err := m.Msg.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DelayBlocks", wireType)
			}
			m.DelayBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DelayBlocks |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDelayMessageResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDelayMessageResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDelayMessageResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
