// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: bitoroprotocol/vest/vest_entry.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	_ "github.com/cosmos/gogoproto/types"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// VestEntry specifies a Vester Account and the rate at which tokens are
// dripped into the corresponding Treasury Account.
type VestEntry struct {
	// The module account to vest tokens from.
	// This is also the key to this `VestEntry` in state.
	VesterAccount string `protobuf:"bytes,1,opt,name=vester_account,json=vesterAccount,proto3" json:"vester_account,omitempty"`
	// The module account to vest tokens to.
	TreasuryAccount string `protobuf:"bytes,2,opt,name=treasury_account,json=treasuryAccount,proto3" json:"treasury_account,omitempty"`
	// The denom of the token to vest.
	Denom string `protobuf:"bytes,3,opt,name=denom,proto3" json:"denom,omitempty"`
	// The start time of vest. Before this time, no vest will occur.
	StartTime time.Time `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3,stdtime" json:"start_time"`
	// The end time of vest. At this target date, all funds should be in the
	// Treasury Account and none left in the Vester Account.
	EndTime time.Time `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3,stdtime" json:"end_time"`
}

func (m *VestEntry) Reset()         { *m = VestEntry{} }
func (m *VestEntry) String() string { return proto.CompactTextString(m) }
func (*VestEntry) ProtoMessage()    {}
func (*VestEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_f64a4a422dc6bf41, []int{0}
}
func (m *VestEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VestEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VestEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VestEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VestEntry.Merge(m, src)
}
func (m *VestEntry) XXX_Size() int {
	return m.Size()
}
func (m *VestEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_VestEntry.DiscardUnknown(m)
}

var xxx_messageInfo_VestEntry proto.InternalMessageInfo

func (m *VestEntry) GetVesterAccount() string {
	if m != nil {
		return m.VesterAccount
	}
	return ""
}

func (m *VestEntry) GetTreasuryAccount() string {
	if m != nil {
		return m.TreasuryAccount
	}
	return ""
}

func (m *VestEntry) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *VestEntry) GetStartTime() time.Time {
	if m != nil {
		return m.StartTime
	}
	return time.Time{}
}

func (m *VestEntry) GetEndTime() time.Time {
	if m != nil {
		return m.EndTime
	}
	return time.Time{}
}

func init() {
	proto.RegisterType((*VestEntry)(nil), "bitoroprotocol.vest.VestEntry")
}

func init() {
	proto.RegisterFile("bitoroprotocol/vest/vest_entry.proto", fileDescriptor_f64a4a422dc6bf41)
}

var fileDescriptor_f64a4a422dc6bf41 = []byte{
	// 312 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0xb3, 0x6a, 0xb5, 0x5d, 0xf1, 0x0f, 0xb1, 0x87, 0xd2, 0x43, 0x5a, 0x44, 0xa1, 0x1e,
	0xcc, 0x82, 0xe2, 0x59, 0xac, 0x78, 0x16, 0x8a, 0x78, 0xf0, 0x52, 0x92, 0x74, 0x4c, 0x83, 0xcd,
	0x4e, 0xd9, 0x9d, 0xa8, 0xfd, 0x16, 0xfd, 0x58, 0x3d, 0xf6, 0xe8, 0x49, 0xa5, 0xf9, 0x14, 0xde,
	0x64, 0x77, 0x49, 0xc1, 0xa3, 0x97, 0x90, 0xfd, 0xcd, 0x7b, 0x8f, 0x7d, 0x3b, 0xfc, 0x24, 0xce,
	0x08, 0x15, 0x4e, 0x15, 0x12, 0x26, 0x38, 0x11, 0xaf, 0xa0, 0xc9, 0x7e, 0x86, 0x20, 0x49, 0xcd,
	0x42, 0x3b, 0xf0, 0x8f, 0xfe, 0xaa, 0x42, 0x23, 0x68, 0x77, 0x52, 0xc4, 0x74, 0x02, 0xc2, 0xd2,
	0xb8, 0x78, 0x16, 0x94, 0xe5, 0xa0, 0x29, 0xca, 0xa7, 0xce, 0xd5, 0x6e, 0xa6, 0x98, 0x3a, 0x8f,
	0x30, 0x7f, 0x8e, 0x1e, 0xff, 0x30, 0xde, 0x78, 0x04, 0x4d, 0x77, 0x26, 0xdf, 0x3f, 0xe5, 0xfb,
	0x26, 0x0c, 0xd4, 0x30, 0x4a, 0x12, 0x2c, 0x24, 0xb5, 0x58, 0x97, 0xf5, 0x1a, 0x83, 0x3d, 0x47,
	0x6f, 0x1c, 0xf4, 0xcf, 0xf8, 0x21, 0x29, 0x88, 0x74, 0xa1, 0x66, 0x6b, 0xe1, 0x86, 0x15, 0x1e,
	0x54, 0xbc, 0x92, 0x36, 0x79, 0x6d, 0x04, 0x12, 0xf3, 0xd6, 0xa6, 0x9d, 0xbb, 0x83, 0x7f, 0xcb,
	0xb9, 0xa6, 0x48, 0xd1, 0xd0, 0x5c, 0xb2, 0xb5, 0xd5, 0x65, 0xbd, 0xdd, 0x8b, 0x76, 0xe8, 0x1a,
	0x84, 0x55, 0x83, 0xf0, 0xa1, 0x6a, 0xd0, 0xaf, 0x2f, 0x3e, 0x3b, 0xde, 0xfc, 0xab, 0xc3, 0x06,
	0x0d, 0xeb, 0x33, 0x13, 0xff, 0x9a, 0xd7, 0x41, 0x8e, 0x5c, 0x44, 0xed, 0x1f, 0x11, 0x3b, 0x20,
	0x47, 0x86, 0xf7, 0xef, 0x17, 0xab, 0x80, 0x2d, 0x57, 0x01, 0xfb, 0x5e, 0x05, 0x6c, 0x5e, 0x06,
	0xde, 0xb2, 0x0c, 0xbc, 0x8f, 0x32, 0xf0, 0x9e, 0xae, 0xd2, 0x8c, 0xc6, 0x45, 0x1c, 0x26, 0x98,
	0x0b, 0xf7, 0xd8, 0xe7, 0x12, 0xe8, 0x0d, 0xd5, 0x8b, 0x48, 0xc6, 0x51, 0x26, 0xc5, 0x7a, 0x43,
	0xef, 0x6e, 0x47, 0x34, 0x9b, 0x82, 0x8e, 0xb7, 0x2d, 0xbe, 0xfc, 0x0d, 0x00, 0x00, 0xff, 0xff,
	0x3d, 0x80, 0x33, 0x1f, 0xc7, 0x01, 0x00, 0x00,
}

func (m *VestEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VestEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VestEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n1, err1 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.EndTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.EndTime):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintVestEntry(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x2a
	n2, err2 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.StartTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.StartTime):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintVestEntry(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x22
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintVestEntry(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.TreasuryAccount) > 0 {
		i -= len(m.TreasuryAccount)
		copy(dAtA[i:], m.TreasuryAccount)
		i = encodeVarintVestEntry(dAtA, i, uint64(len(m.TreasuryAccount)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.VesterAccount) > 0 {
		i -= len(m.VesterAccount)
		copy(dAtA[i:], m.VesterAccount)
		i = encodeVarintVestEntry(dAtA, i, uint64(len(m.VesterAccount)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintVestEntry(dAtA []byte, offset int, v uint64) int {
	offset -= sovVestEntry(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *VestEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.VesterAccount)
	if l > 0 {
		n += 1 + l + sovVestEntry(uint64(l))
	}
	l = len(m.TreasuryAccount)
	if l > 0 {
		n += 1 + l + sovVestEntry(uint64(l))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovVestEntry(uint64(l))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.StartTime)
	n += 1 + l + sovVestEntry(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.EndTime)
	n += 1 + l + sovVestEntry(uint64(l))
	return n
}

func sovVestEntry(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozVestEntry(x uint64) (n int) {
	return sovVestEntry(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *VestEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVestEntry
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VestEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VestEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VesterAccount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVestEntry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVestEntry
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVestEntry
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VesterAccount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TreasuryAccount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVestEntry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVestEntry
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVestEntry
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TreasuryAccount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVestEntry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVestEntry
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVestEntry
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVestEntry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthVestEntry
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthVestEntry
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.StartTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVestEntry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthVestEntry
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthVestEntry
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.EndTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipVestEntry(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthVestEntry
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipVestEntry(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowVestEntry
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVestEntry
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVestEntry
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthVestEntry
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupVestEntry
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthVestEntry
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthVestEntry        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowVestEntry          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupVestEntry = fmt.Errorf("proto: unexpected end of group")
)
