FROM bitoroprotocol-base

COPY ./testing/snapshotting/snapshot.sh /bitoroprotocol/snapshot.sh

RUN go install cosmossdk.io/tools/cosmovisor/cmd/cosmovisor@v1.5.0
RUN apk add --no-cache bash jq aws-cli

ENTRYPOINT ["/bitoroprotocol/snapshot.sh"]
