// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: bitoroprotocol/affiliates/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Message to register a referee-affiliate relationship
type MsgRegisterAffiliate struct {
	// Address of the referee
	Referee string `protobuf:"bytes,1,opt,name=referee,proto3" json:"referee,omitempty"`
	// Address of the affiliate
	Affiliate string `protobuf:"bytes,2,opt,name=affiliate,proto3" json:"affiliate,omitempty"`
}

func (m *MsgRegisterAffiliate) Reset()         { *m = MsgRegisterAffiliate{} }
func (m *MsgRegisterAffiliate) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterAffiliate) ProtoMessage()    {}
func (*MsgRegisterAffiliate) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a1b43c1d100550f, []int{0}
}
func (m *MsgRegisterAffiliate) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterAffiliate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterAffiliate.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterAffiliate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterAffiliate.Merge(m, src)
}
func (m *MsgRegisterAffiliate) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterAffiliate) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterAffiliate.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterAffiliate proto.InternalMessageInfo

// Response to MsgRegisterAffiliate
type MsgRegisterAffiliateResponse struct {
}

func (m *MsgRegisterAffiliateResponse) Reset()         { *m = MsgRegisterAffiliateResponse{} }
func (m *MsgRegisterAffiliateResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterAffiliateResponse) ProtoMessage()    {}
func (*MsgRegisterAffiliateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a1b43c1d100550f, []int{1}
}
func (m *MsgRegisterAffiliateResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterAffiliateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterAffiliateResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterAffiliateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterAffiliateResponse.Merge(m, src)
}
func (m *MsgRegisterAffiliateResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterAffiliateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterAffiliateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterAffiliateResponse proto.InternalMessageInfo

// Message to update affiliate tiers
type MsgUpdateAffiliateTiers struct {
	// Authority sending this message. Will be sent by gov
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// Updated affiliate tiers information
	Tiers AffiliateTiers `protobuf:"bytes,2,opt,name=tiers,proto3" json:"tiers"`
}

func (m *MsgUpdateAffiliateTiers) Reset()         { *m = MsgUpdateAffiliateTiers{} }
func (m *MsgUpdateAffiliateTiers) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateAffiliateTiers) ProtoMessage()    {}
func (*MsgUpdateAffiliateTiers) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a1b43c1d100550f, []int{2}
}
func (m *MsgUpdateAffiliateTiers) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateAffiliateTiers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateAffiliateTiers.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateAffiliateTiers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateAffiliateTiers.Merge(m, src)
}
func (m *MsgUpdateAffiliateTiers) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateAffiliateTiers) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateAffiliateTiers.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateAffiliateTiers proto.InternalMessageInfo

func (m *MsgUpdateAffiliateTiers) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateAffiliateTiers) GetTiers() AffiliateTiers {
	if m != nil {
		return m.Tiers
	}
	return AffiliateTiers{}
}

// Response to MsgUpdateAffiliateTiers
type MsgUpdateAffiliateTiersResponse struct {
}

func (m *MsgUpdateAffiliateTiersResponse) Reset()         { *m = MsgUpdateAffiliateTiersResponse{} }
func (m *MsgUpdateAffiliateTiersResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateAffiliateTiersResponse) ProtoMessage()    {}
func (*MsgUpdateAffiliateTiersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a1b43c1d100550f, []int{3}
}
func (m *MsgUpdateAffiliateTiersResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateAffiliateTiersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateAffiliateTiersResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateAffiliateTiersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateAffiliateTiersResponse.Merge(m, src)
}
func (m *MsgUpdateAffiliateTiersResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateAffiliateTiersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateAffiliateTiersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateAffiliateTiersResponse proto.InternalMessageInfo

// Message to update affiliate whitelist
type MsgUpdateAffiliateWhitelist struct {
	// Authority sending this message. Will be sent by gov
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// Updated affiliate whitelist information
	Whitelist AffiliateWhitelist `protobuf:"bytes,2,opt,name=whitelist,proto3" json:"whitelist"`
}

func (m *MsgUpdateAffiliateWhitelist) Reset()         { *m = MsgUpdateAffiliateWhitelist{} }
func (m *MsgUpdateAffiliateWhitelist) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateAffiliateWhitelist) ProtoMessage()    {}
func (*MsgUpdateAffiliateWhitelist) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a1b43c1d100550f, []int{4}
}
func (m *MsgUpdateAffiliateWhitelist) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateAffiliateWhitelist) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateAffiliateWhitelist.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateAffiliateWhitelist) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateAffiliateWhitelist.Merge(m, src)
}
func (m *MsgUpdateAffiliateWhitelist) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateAffiliateWhitelist) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateAffiliateWhitelist.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateAffiliateWhitelist proto.InternalMessageInfo

func (m *MsgUpdateAffiliateWhitelist) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateAffiliateWhitelist) GetWhitelist() AffiliateWhitelist {
	if m != nil {
		return m.Whitelist
	}
	return AffiliateWhitelist{}
}

// Response to MsgUpdateAffiliateWhitelist
type MsgUpdateAffiliateWhitelistResponse struct {
}

func (m *MsgUpdateAffiliateWhitelistResponse) Reset()         { *m = MsgUpdateAffiliateWhitelistResponse{} }
func (m *MsgUpdateAffiliateWhitelistResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateAffiliateWhitelistResponse) ProtoMessage()    {}
func (*MsgUpdateAffiliateWhitelistResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a1b43c1d100550f, []int{5}
}
func (m *MsgUpdateAffiliateWhitelistResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateAffiliateWhitelistResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateAffiliateWhitelistResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateAffiliateWhitelistResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateAffiliateWhitelistResponse.Merge(m, src)
}
func (m *MsgUpdateAffiliateWhitelistResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateAffiliateWhitelistResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateAffiliateWhitelistResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateAffiliateWhitelistResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgRegisterAffiliate)(nil), "bitoroprotocol.affiliates.MsgRegisterAffiliate")
	proto.RegisterType((*MsgRegisterAffiliateResponse)(nil), "bitoroprotocol.affiliates.MsgRegisterAffiliateResponse")
	proto.RegisterType((*MsgUpdateAffiliateTiers)(nil), "bitoroprotocol.affiliates.MsgUpdateAffiliateTiers")
	proto.RegisterType((*MsgUpdateAffiliateTiersResponse)(nil), "bitoroprotocol.affiliates.MsgUpdateAffiliateTiersResponse")
	proto.RegisterType((*MsgUpdateAffiliateWhitelist)(nil), "bitoroprotocol.affiliates.MsgUpdateAffiliateWhitelist")
	proto.RegisterType((*MsgUpdateAffiliateWhitelistResponse)(nil), "bitoroprotocol.affiliates.MsgUpdateAffiliateWhitelistResponse")
}

func init() {
	proto.RegisterFile("bitoroprotocol/affiliates/tx.proto", fileDescriptor_7a1b43c1d100550f)
}

var fileDescriptor_7a1b43c1d100550f = []byte{
	// 478 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x4b, 0x8b, 0xd3, 0x40,
	0x1c, 0xcf, 0xb8, 0x3e, 0xe8, 0x08, 0x82, 0x21, 0xb0, 0xd9, 0x28, 0x89, 0x46, 0x04, 0x5d, 0x68,
	0x06, 0x23, 0x28, 0x54, 0x10, 0xb6, 0xe0, 0xb1, 0x07, 0xa3, 0x8b, 0xe0, 0x45, 0xd2, 0x74, 0x3a,
	0x19, 0x6c, 0x33, 0x61, 0x66, 0xd6, 0xdd, 0x3d, 0x78, 0xf1, 0x20, 0x1e, 0xc5, 0x93, 0xc7, 0xc5,
	0x93, 0x47, 0x0f, 0x1e, 0xfc, 0x08, 0x7b, 0x2c, 0x9e, 0x3c, 0x89, 0xb4, 0x07, 0xfd, 0x18, 0x92,
	0x37, 0xa5, 0x49, 0xbb, 0xed, 0x29, 0x93, 0xf9, 0xff, 0x9e, 0xcc, 0x30, 0xd0, 0xee, 0x53, 0xc9,
	0x38, 0x8b, 0x39, 0x93, 0x2c, 0x60, 0x23, 0xe4, 0x0f, 0x87, 0x74, 0x44, 0x7d, 0x89, 0x05, 0x92,
	0x47, 0x4e, 0xba, 0xad, 0xee, 0xcc, 0x63, 0x9c, 0x0a, 0x63, 0xec, 0x04, 0x4c, 0x8c, 0x99, 0x78,
	0x95, 0xce, 0x50, 0xf6, 0x93, 0xb1, 0x0c, 0x8d, 0x30, 0x92, 0x71, 0x50, 0xb2, 0xca, 0x77, 0x77,
	0x9b, 0xfd, 0xaa, 0x65, 0x8e, 0xdd, 0xce, 0xf4, 0xd0, 0x58, 0x10, 0xf4, 0xe6, 0x5e, 0xf2, 0xc9,
	0x06, 0xf6, 0x67, 0x00, 0xb5, 0x9e, 0x20, 0x1e, 0x26, 0x54, 0x48, 0xcc, 0xf7, 0x0a, 0xa2, 0xea,
	0xc2, 0x4b, 0x1c, 0x0f, 0x31, 0xc7, 0x58, 0x07, 0x37, 0xc0, 0x9d, 0x56, 0x57, 0xff, 0xf9, 0xbd,
	0xad, 0xe5, 0xb1, 0xf6, 0x06, 0x03, 0x8e, 0x85, 0x78, 0x26, 0x39, 0x8d, 0x88, 0x57, 0x00, 0xd5,
	0x07, 0xb0, 0x55, 0x3a, 0xeb, 0xe7, 0x56, 0xb0, 0x2a, 0x68, 0x47, 0xfb, 0x70, 0x62, 0x29, 0xff,
	0x4e, 0x2c, 0xe5, 0xdd, 0xdf, 0x6f, 0xbb, 0x85, 0x9a, 0x6d, 0xc2, 0xeb, 0x75, 0xc9, 0x3c, 0x2c,
	0x62, 0x16, 0x09, 0x6c, 0x7f, 0x05, 0x70, 0xbb, 0x27, 0xc8, 0x7e, 0x3c, 0xf0, 0x25, 0x2e, 0xc7,
	0xcf, 0x29, 0xe6, 0x22, 0x4d, 0x72, 0x20, 0x43, 0xc6, 0xa9, 0x3c, 0x5e, 0x99, 0xbf, 0x82, 0xaa,
	0x4f, 0xe0, 0x05, 0x99, 0x08, 0xa4, 0xe9, 0x2f, 0xbb, 0x77, 0x9d, 0xc6, 0xf3, 0x72, 0xe6, 0x1d,
	0xbb, 0xe7, 0x4f, 0x7f, 0x5b, 0x8a, 0x97, 0xb1, 0x3b, 0x57, 0x92, 0x22, 0x95, 0xac, 0x7d, 0x13,
	0x5a, 0x0d, 0x49, 0xcb, 0x36, 0x3f, 0x00, 0xbc, 0xb6, 0x88, 0x79, 0x11, 0x52, 0x89, 0x47, 0x54,
	0xc8, 0x8d, 0x1b, 0x3d, 0x85, 0xad, 0xc3, 0x42, 0x24, 0x6f, 0xd5, 0x3e, 0x4b, 0xab, 0xd2, 0x39,
	0x6f, 0x56, 0xa9, 0x2c, 0xb4, 0xbb, 0x0d, 0x6f, 0x2d, 0x49, 0x5e, 0x34, 0x74, 0xbf, 0x6c, 0xc1,
	0xad, 0x9e, 0x20, 0xea, 0x5b, 0x78, 0x75, 0xf1, 0xba, 0xa1, 0x25, 0x99, 0xea, 0x6e, 0x81, 0xf1,
	0x70, 0x4d, 0x42, 0x11, 0x43, 0x7d, 0x0f, 0xa0, 0x56, 0x7b, 0x67, 0xdc, 0xe5, 0x8a, 0x75, 0x1c,
	0xa3, 0xb3, 0x3e, 0xa7, 0x0c, 0xf2, 0x09, 0x40, 0xbd, 0xf9, 0xb8, 0xd7, 0x12, 0x2e, 0x79, 0xc6,
	0xe3, 0xcd, 0x78, 0x45, 0xa8, 0xee, 0xfe, 0xe9, 0xd4, 0x04, 0x93, 0xa9, 0x09, 0xfe, 0x4c, 0x4d,
	0xf0, 0x71, 0x66, 0x2a, 0x93, 0x99, 0xa9, 0xfc, 0x9a, 0x99, 0xca, 0xcb, 0x47, 0x84, 0xca, 0xf0,
	0xa0, 0xef, 0x04, 0x6c, 0x8c, 0x32, 0x8f, 0x76, 0x84, 0xe5, 0x21, 0xe3, 0xaf, 0x51, 0x10, 0xfa,
	0x34, 0x42, 0xe5, 0x43, 0x74, 0x34, 0xf7, 0xf4, 0x1d, 0xc7, 0x58, 0xf4, 0x2f, 0xa6, 0xc3, 0xfb,
	0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0x73, 0xa6, 0x51, 0x98, 0x24, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// RegisterAffiliate registers a referee-affiliate relationship
	RegisterAffiliate(ctx context.Context, in *MsgRegisterAffiliate, opts ...grpc.CallOption) (*MsgRegisterAffiliateResponse, error)
	// UpdateAffiliateTiers updates affiliate tiers
	UpdateAffiliateTiers(ctx context.Context, in *MsgUpdateAffiliateTiers, opts ...grpc.CallOption) (*MsgUpdateAffiliateTiersResponse, error)
	// UpdateAffiliateWhitelist updates affiliate whitelist
	UpdateAffiliateWhitelist(ctx context.Context, in *MsgUpdateAffiliateWhitelist, opts ...grpc.CallOption) (*MsgUpdateAffiliateWhitelistResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) RegisterAffiliate(ctx context.Context, in *MsgRegisterAffiliate, opts ...grpc.CallOption) (*MsgRegisterAffiliateResponse, error) {
	out := new(MsgRegisterAffiliateResponse)
	err := c.cc.Invoke(ctx, "/bitoroprotocol.affiliates.Msg/RegisterAffiliate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateAffiliateTiers(ctx context.Context, in *MsgUpdateAffiliateTiers, opts ...grpc.CallOption) (*MsgUpdateAffiliateTiersResponse, error) {
	out := new(MsgUpdateAffiliateTiersResponse)
	err := c.cc.Invoke(ctx, "/bitoroprotocol.affiliates.Msg/UpdateAffiliateTiers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateAffiliateWhitelist(ctx context.Context, in *MsgUpdateAffiliateWhitelist, opts ...grpc.CallOption) (*MsgUpdateAffiliateWhitelistResponse, error) {
	out := new(MsgUpdateAffiliateWhitelistResponse)
	err := c.cc.Invoke(ctx, "/bitoroprotocol.affiliates.Msg/UpdateAffiliateWhitelist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// RegisterAffiliate registers a referee-affiliate relationship
	RegisterAffiliate(context.Context, *MsgRegisterAffiliate) (*MsgRegisterAffiliateResponse, error)
	// UpdateAffiliateTiers updates affiliate tiers
	UpdateAffiliateTiers(context.Context, *MsgUpdateAffiliateTiers) (*MsgUpdateAffiliateTiersResponse, error)
	// UpdateAffiliateWhitelist updates affiliate whitelist
	UpdateAffiliateWhitelist(context.Context, *MsgUpdateAffiliateWhitelist) (*MsgUpdateAffiliateWhitelistResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) RegisterAffiliate(ctx context.Context, req *MsgRegisterAffiliate) (*MsgRegisterAffiliateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterAffiliate not implemented")
}
func (*UnimplementedMsgServer) UpdateAffiliateTiers(ctx context.Context, req *MsgUpdateAffiliateTiers) (*MsgUpdateAffiliateTiersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAffiliateTiers not implemented")
}
func (*UnimplementedMsgServer) UpdateAffiliateWhitelist(ctx context.Context, req *MsgUpdateAffiliateWhitelist) (*MsgUpdateAffiliateWhitelistResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAffiliateWhitelist not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_RegisterAffiliate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterAffiliate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterAffiliate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bitoroprotocol.affiliates.Msg/RegisterAffiliate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterAffiliate(ctx, req.(*MsgRegisterAffiliate))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateAffiliateTiers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateAffiliateTiers)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateAffiliateTiers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bitoroprotocol.affiliates.Msg/UpdateAffiliateTiers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateAffiliateTiers(ctx, req.(*MsgUpdateAffiliateTiers))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateAffiliateWhitelist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateAffiliateWhitelist)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateAffiliateWhitelist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bitoroprotocol.affiliates.Msg/UpdateAffiliateWhitelist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateAffiliateWhitelist(ctx, req.(*MsgUpdateAffiliateWhitelist))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bitoroprotocol.affiliates.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterAffiliate",
			Handler:    _Msg_RegisterAffiliate_Handler,
		},
		{
			MethodName: "UpdateAffiliateTiers",
			Handler:    _Msg_UpdateAffiliateTiers_Handler,
		},
		{
			MethodName: "UpdateAffiliateWhitelist",
			Handler:    _Msg_UpdateAffiliateWhitelist_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bitoroprotocol/affiliates/tx.proto",
}

func (m *MsgRegisterAffiliate) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterAffiliate) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterAffiliate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Affiliate) > 0 {
		i -= len(m.Affiliate)
		copy(dAtA[i:], m.Affiliate)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Affiliate)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Referee) > 0 {
		i -= len(m.Referee)
		copy(dAtA[i:], m.Referee)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Referee)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRegisterAffiliateResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterAffiliateResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterAffiliateResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdateAffiliateTiers) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateAffiliateTiers) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateAffiliateTiers) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Tiers.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateAffiliateTiersResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateAffiliateTiersResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateAffiliateTiersResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdateAffiliateWhitelist) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateAffiliateWhitelist) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateAffiliateWhitelist) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Whitelist.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateAffiliateWhitelistResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateAffiliateWhitelistResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateAffiliateWhitelistResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgRegisterAffiliate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Referee)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Affiliate)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRegisterAffiliateResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdateAffiliateTiers) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Tiers.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateAffiliateTiersResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdateAffiliateWhitelist) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Whitelist.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateAffiliateWhitelistResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgRegisterAffiliate) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterAffiliate: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterAffiliate: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Referee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Referee = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Affiliate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Affiliate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegisterAffiliateResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterAffiliateResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterAffiliateResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateAffiliateTiers) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateAffiliateTiers: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateAffiliateTiers: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tiers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Tiers.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateAffiliateTiersResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateAffiliateTiersResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateAffiliateTiersResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateAffiliateWhitelist) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateAffiliateWhitelist: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateAffiliateWhitelist: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Whitelist", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Whitelist.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateAffiliateWhitelistResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateAffiliateWhitelistResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateAffiliateWhitelistResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
