// This file is @generated by prost-build.
pub mod cosmos {
    pub mod base {
        pub mod query {
            pub mod v1beta1 {
                include!("cosmos.base.query.v1beta1.rs");
            }
        }
        pub mod v1beta1 {
            include!("cosmos.base.v1beta1.rs");
        }
    }
}
pub mod cosmos_proto {
    include!("cosmos_proto.rs");
}
pub mod bitoroprotocol {
    pub mod accountplus {
        include!("bitoroprotocol.accountplus.rs");
    }
    pub mod affiliates {
        include!("bitoroprotocol.affiliates.rs");
    }
    pub mod assets {
        include!("bitoroprotocol.assets.rs");
    }
    pub mod blocktime {
        include!("bitoroprotocol.blocktime.rs");
    }
    pub mod bridge {
        include!("bitoroprotocol.bridge.rs");
    }
    pub mod clob {
        include!("bitoroprotocol.clob.rs");
    }
    pub mod daemons {
        pub mod bridge {
            include!("bitoroprotocol.daemons.bridge.rs");
        }
        pub mod liquidation {
            include!("bitoroprotocol.daemons.liquidation.rs");
        }
        pub mod pricefeed {
            include!("bitoroprotocol.daemons.pricefeed.rs");
        }
    }
    pub mod delaymsg {
        include!("bitoroprotocol.delaymsg.rs");
    }
    pub mod epochs {
        include!("bitoroprotocol.epochs.rs");
    }
    pub mod feetiers {
        include!("bitoroprotocol.feetiers.rs");
    }
    pub mod govplus {
        include!("bitoroprotocol.govplus.rs");
    }
    pub mod indexer {
        pub mod events {
            include!("bitoroprotocol.indexer.events.rs");
        }
        pub mod indexer_manager {
            include!("bitoroprotocol.indexer.indexer_manager.rs");
        }
        pub mod off_chain_updates {
            include!("bitoroprotocol.indexer.off_chain_updates.rs");
        }
        pub mod protocol {
            pub mod v1 {
                include!("bitoroprotocol.indexer.protocol.v1.rs");
            }
        }
        pub mod redis {
            include!("bitoroprotocol.indexer.redis.rs");
        }
        pub mod shared {
            include!("bitoroprotocol.indexer.shared.rs");
        }
        pub mod socks {
            include!("bitoroprotocol.indexer.socks.rs");
        }
    }
    pub mod listing {
        include!("bitoroprotocol.listing.rs");
    }
    pub mod perpetuals {
        include!("bitoroprotocol.perpetuals.rs");
    }
    pub mod prices {
        include!("bitoroprotocol.prices.rs");
    }
    pub mod ratelimit {
        include!("bitoroprotocol.ratelimit.rs");
    }
    pub mod revshare {
        include!("bitoroprotocol.revshare.rs");
    }
    pub mod rewards {
        include!("bitoroprotocol.rewards.rs");
    }
    pub mod sending {
        include!("bitoroprotocol.sending.rs");
    }
    pub mod stats {
        include!("bitoroprotocol.stats.rs");
    }
    pub mod subaccounts {
        include!("bitoroprotocol.subaccounts.rs");
    }
    pub mod vault {
        include!("bitoroprotocol.vault.rs");
    }
    pub mod vest {
        include!("bitoroprotocol.vest.rs");
    }
}
pub mod google {
    pub mod api {
        include!("google.api.rs");
    }
}
