// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: bitoroprotocol/bridge/bridge_event.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// BridgeEvent is a recognized event from the Ethereum blockchain.
type BridgeEvent struct {
	// The unique id of the Ethereum event log.
	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// The tokens bridged.
	Coin types.Coin `protobuf:"bytes,2,opt,name=coin,proto3" json:"coin"`
	// The account address or module address to bridge to.
	Address string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	// The Ethereum block height of the event.
	EthBlockHeight uint64 `protobuf:"varint,4,opt,name=eth_block_height,json=ethBlockHeight,proto3" json:"eth_block_height,omitempty"`
}

func (m *BridgeEvent) Reset()         { *m = BridgeEvent{} }
func (m *BridgeEvent) String() string { return proto.CompactTextString(m) }
func (*BridgeEvent) ProtoMessage()    {}
func (*BridgeEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d0bc475d063c872, []int{0}
}
func (m *BridgeEvent) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BridgeEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BridgeEvent.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BridgeEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BridgeEvent.Merge(m, src)
}
func (m *BridgeEvent) XXX_Size() int {
	return m.Size()
}
func (m *BridgeEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_BridgeEvent.DiscardUnknown(m)
}

var xxx_messageInfo_BridgeEvent proto.InternalMessageInfo

func (m *BridgeEvent) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BridgeEvent) GetCoin() types.Coin {
	if m != nil {
		return m.Coin
	}
	return types.Coin{}
}

func (m *BridgeEvent) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *BridgeEvent) GetEthBlockHeight() uint64 {
	if m != nil {
		return m.EthBlockHeight
	}
	return 0
}

func init() {
	proto.RegisterType((*BridgeEvent)(nil), "bitoroprotocol.bridge.BridgeEvent")
}

func init() {
	proto.RegisterFile("bitoroprotocol/bridge/bridge_event.proto", fileDescriptor_5d0bc475d063c872)
}

var fileDescriptor_5d0bc475d063c872 = []byte{
	// 316 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xb1, 0x4e, 0xeb, 0x30,
	0x14, 0x86, 0xe3, 0xde, 0xe8, 0x22, 0x52, 0x51, 0xa1, 0xa8, 0x48, 0x69, 0x07, 0x13, 0x31, 0x65,
	0x69, 0xac, 0xb6, 0x03, 0x33, 0x41, 0x48, 0xac, 0x84, 0x8d, 0x25, 0x8a, 0x13, 0x2b, 0xb6, 0xda,
	0xfa, 0x54, 0xb6, 0x29, 0xf0, 0x16, 0x3c, 0x0a, 0x03, 0x0f, 0xd1, 0xb1, 0x62, 0x62, 0x42, 0xa8,
	0x79, 0x11, 0x94, 0x38, 0x45, 0x62, 0xb2, 0xcf, 0xf9, 0x3e, 0xff, 0x96, 0x7e, 0x2f, 0xa2, 0xc2,
	0x80, 0x82, 0xb5, 0x02, 0x03, 0x05, 0x2c, 0x09, 0x55, 0xa2, 0xac, 0x58, 0x77, 0x64, 0x6c, 0xc3,
	0xa4, 0x89, 0x5b, 0xe8, 0x9f, 0xfd, 0x35, 0x63, 0xab, 0x8c, 0x87, 0x15, 0x54, 0x76, 0x49, 0x9a,
	0x9b, 0x95, 0xc7, 0xa3, 0x02, 0xf4, 0x0a, 0x74, 0x66, 0x81, 0x1d, 0x3a, 0x84, 0xed, 0x44, 0x68,
	0xae, 0x19, 0xd9, 0x4c, 0x29, 0x33, 0xf9, 0x94, 0x14, 0x20, 0xa4, 0xe5, 0x17, 0x6f, 0xc8, 0xeb,
	0x27, 0x6d, 0xf6, 0x4d, 0xf3, 0xbb, 0x3f, 0xf0, 0x7a, 0xa2, 0x0c, 0x50, 0x88, 0xa2, 0x93, 0xb4,
	0x27, 0x4a, 0x7f, 0xee, 0xb9, 0x8d, 0x1d, 0xf4, 0x42, 0x14, 0xf5, 0x67, 0xa3, 0xb8, 0x0b, 0x6f,
	0xe2, 0xe2, 0x2e, 0x2e, 0xbe, 0x06, 0x21, 0x13, 0x77, 0xfb, 0x75, 0xee, 0xa4, 0xad, 0xec, 0xcf,
	0xbc, 0xa3, 0xbc, 0x2c, 0x15, 0xd3, 0x3a, 0xf8, 0x17, 0xa2, 0xe8, 0x38, 0x09, 0x3e, 0xde, 0x27,
	0xc3, 0xee, 0xe9, 0x95, 0x25, 0xf7, 0x46, 0x09, 0x59, 0xa5, 0x07, 0xd1, 0x8f, 0xbc, 0x53, 0x66,
	0x78, 0x46, 0x97, 0x50, 0x2c, 0x32, 0xce, 0x44, 0xc5, 0x4d, 0xe0, 0x86, 0x28, 0x72, 0xd3, 0x01,
	0x33, 0x3c, 0x69, 0xd6, 0xb7, 0xed, 0x36, 0xb9, 0xdb, 0xee, 0x31, 0xda, 0xed, 0x31, 0xfa, 0xde,
	0x63, 0xf4, 0x5a, 0x63, 0x67, 0x57, 0x63, 0xe7, 0xb3, 0xc6, 0xce, 0xc3, 0x65, 0x25, 0x0c, 0x7f,
	0xa4, 0x71, 0x01, 0x2b, 0x62, 0xfb, 0x9b, 0x48, 0x66, 0x9e, 0x40, 0x2d, 0x48, 0xc1, 0x73, 0x21,
	0xc9, 0x6f, 0xf1, 0xcf, 0x87, 0xea, 0xcd, 0xcb, 0x9a, 0x69, 0xfa, 0xbf, 0x05, 0xf3, 0x9f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x66, 0xfd, 0xcb, 0x52, 0xa0, 0x01, 0x00, 0x00,
}

func (m *BridgeEvent) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BridgeEvent) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BridgeEvent) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.EthBlockHeight != 0 {
		i = encodeVarintBridgeEvent(dAtA, i, uint64(m.EthBlockHeight))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintBridgeEvent(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x1a
	}
	{
		size, err := m.Coin.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintBridgeEvent(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.Id != 0 {
		i = encodeVarintBridgeEvent(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintBridgeEvent(dAtA []byte, offset int, v uint64) int {
	offset -= sovBridgeEvent(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *BridgeEvent) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovBridgeEvent(uint64(m.Id))
	}
	l = m.Coin.Size()
	n += 1 + l + sovBridgeEvent(uint64(l))
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovBridgeEvent(uint64(l))
	}
	if m.EthBlockHeight != 0 {
		n += 1 + sovBridgeEvent(uint64(m.EthBlockHeight))
	}
	return n
}

func sovBridgeEvent(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozBridgeEvent(x uint64) (n int) {
	return sovBridgeEvent(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *BridgeEvent) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBridgeEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BridgeEvent: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BridgeEvent: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBridgeEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Coin", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBridgeEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBridgeEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBridgeEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Coin.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBridgeEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBridgeEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBridgeEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EthBlockHeight", wireType)
			}
			m.EthBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBridgeEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EthBlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipBridgeEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBridgeEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipBridgeEvent(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowBridgeEvent
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBridgeEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBridgeEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthBridgeEvent
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupBridgeEvent
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthBridgeEvent
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthBridgeEvent        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowBridgeEvent          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupBridgeEvent = fmt.Errorf("proto: unexpected end of group")
)
